menu:
  Datapacks: https://gm4.co
  Twitter: https://gm4.co/twitter
  Wiki: https://wiki.gm4.co
  Discord: https://gm4.co/twitter
  GitHub: https://github.com/Gamemode4Dev
  Credits: /credits
  